# Generated by Django 3.1.7 on 2021-07-28 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cat_doc',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='cat_doc',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
