# Generated by Django 3.1.7 on 2021-07-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='cat_doc',
            new_name='brand_doc',
        ),
    ]
