# Generated by Django 3.1.7 on 2021-07-29 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0010_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_doc',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_product', to='datawork.product'),
        ),
    ]
