# Generated by Django 3.1.7 on 2021-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0011_auto_20210729_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
