# Generated by Django 3.1.7 on 2021-07-31 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0013_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
