# Generated by Django 3.1.7 on 2021-07-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0014_remove_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='customer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
