# Generated by Django 3.1.7 on 2021-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0015_auto_20210731_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_qty',
            field=models.IntegerField(null=True),
        ),
    ]
