# Generated by Django 3.1.7 on 2021-07-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0017_auto_20210731_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
