# Generated by Django 3.1.7 on 2021-07-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0018_auto_20210731_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_product',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_product',
            field=models.ManyToManyField(null=True, to='datawork.Product'),
        ),
    ]
