# Generated by Django 3.1.7 on 2021-07-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0019_auto_20210731_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_product',
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_product', to='datawork.product'),
        ),
    ]
