# Generated by Django 3.1.7 on 2021-08-02 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0023_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='cat',
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_doc',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
