# Generated by Django 3.1.7 on 2021-08-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0028_auto_20210802_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
