# Generated by Django 3.1.7 on 2021-08-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0030_auto_20210809_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
