# Generated by Django 3.1.7 on 2021-08-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0031_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
