# Generated by Django 3.1.7 on 2021-08-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0033_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
