# Generated by Django 3.1.7 on 2021-08-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0038_remove_order_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
