# Generated by Django 3.1.7 on 2021-08-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0040_auto_20210810_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datawork.customer'),
        ),
    ]
