# Generated by Django 3.1.7 on 2021-08-10 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0041_order_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
