# Generated by Django 3.1.7 on 2021-08-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0042_remove_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact',
        ),
    ]
