# Generated by Django 3.1.7 on 2021-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0044_auto_20210811_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('credit', 'credit'), ('cash', 'cash')], max_length=100, null=True),
        ),
    ]
