# Generated by Django 3.1.7 on 2021-08-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0046_auto_20210812_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
