# Generated by Django 3.1.7 on 2021-08-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0047_order_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_method',
        ),
    ]
