# Generated by Django 3.1.7 on 2021-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0048_remove_order_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Paid', 'Paid')], max_length=100, null=True),
        ),
    ]
