# Generated by Django 3.1.7 on 2021-08-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0053_orderpro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPro',
        ),
    ]
