# Generated by Django 3.1.7 on 2021-08-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0054_delete_orderpro'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_cxategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datawork.category'),
        ),
    ]
