# Generated by Django 3.1.7 on 2021-09-07 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0056_thickness_thick_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thickness',
            name='thick_category',
        ),
        migrations.AddField(
            model_name='thickness',
            name='thick_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datawork.brand'),
        ),
    ]
