# Generated by Django 3.1.7 on 2021-09-07 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0057_auto_20210907_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size_category',
        ),
        migrations.AddField(
            model_name='size',
            name='size_thick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datawork.thickness'),
        ),
    ]
